### ISSUE TITLE
Change so that you can see what each input is after filling 

### ISSUE THREAD

**Issue by j2wed09** [tysonfaulkner/time#64]
![screenshot from 2018-06-06 16-28-26](https://user-images.githubusercontent.com/36715911/41070265-ad2224a8-69a6-11e8-8054-1ecb15a3d7e0.png)

**Comment by tysonfaulkner** [comment]
@j2wed09 I'd like to design the input page on the whiteboard to make it flow and look nice. Maybe break into steps? Or make linear down the page?
